### ISSUE TITLE
Revamp text rendering

### ISSUE THREAD

**Issue by einarf** [pythonarcade/arcade#851]
# Text Rendering

**NOTE: This task depends on #850. Both features needs to be implemented for this to even work.**

## Curren State

Currently `arcade.draw_text()` creates an `arcade.Texture` of the entire text string, adds it to a sprite and caches a `SpriteList` for this specific text instance. This is great for static text, but displaying counters or anything that produces a lot of unique strings will cause arcade to allocate a lot of system and graphics memory. The process of creating new text instances are also not fast enough in these instances to give the user a smooth experience (framerate). Displaying fps counters, point counters and whatnot can cause the whole application to lag badly. Worst case it can fill the entire system memory and graphics memory eventually crashing.

## New System (suggestion)

**We cannot introduce this change without texture atlases (#850) and we cannot introduce texture atlases unless we also improve text rendering. If we keep the old text redering the global atlas will be filled to the brim with text textures.**

A new text rendering system will create and cache individual glyphs into a texture atlas. Preferably using pyglet's sytem for loading glyph data. `arcade.draw_text()` will no longer return a `Sprite`. The function will simply draw the text to the current redering target (usually the screen).

The first iteration can be very simple. It might be useful to create some generic textrederer class/system that can also support custom glyph atlases. This is useful when users have their own bitmapped fonts. We possibly even provide a simple default bitmapped font in the arcade resources. It will provide a exceptionally fast way to deal with text.

We can possibly re-add the old `arcade.create_text()` method (it was removed in the past). This would work just like the current `arcade.draw_text()` by rendering the text into a texture and attaching it to a sprite. We'll emulate the this by drawing text to a framebuffer object with a texture attachment and `read()` this texture into a PIL `Image`. **We need to make it absolutely clear that this method should be used sparingly. Reserved for cases were you need static text entries in spritelist for some reason.

## TODO

Remaining work

- [ ] Complete `Text` object
- [x] Profile `draw_text` and figure out if label caching is effective
- [x] Profile `create_text` drawing vs `draw_text`
- [x] Does font selection and font size work?
- [x] Can we make pyglet and arcade rendering more compatible? (`Context.pyglet_rendering`)
- [x] Fix issue with buffer binding in pyglet corrupting arcade geometry. This includes binding to index buffer slot and unbinding in general.

**Comment by asherstuhlman** [comment]
Requesting word-wrap as an option for text in the revamped rendering system :)

**Comment by invalidenumerant** [comment]
so is there a way, using the current draw_text(), to render the font without smoothing/antialiasing? I'm trying to use this https://www.kreativekorp.com/software/fonts/apple2.shtml Apple IIe font, but it shows up blurry no matter what font_size I use.

**Comment by invalidenumerant** [comment]
wait, is it as simple as modifying draw_text() to use GL_NEAREST when it calls draw()?

@asherstuhlman btw the textwrap function works really well with draw_text

**Comment by einarf** [comment]
@invalidenumerant We do have a discord server linked in docs : https://discord.gg/ZjGDqMp

Easier to get answers there.

**Comment by einarf** [comment]
The core of what we wanted is completed here, Closing this for now. #433 covers alot of what is remaining,
