### ISSUE TITLE
Documentation Revamp

### ISSUE THREAD

**Issue by einarf** [pythonarcade/arcade#873]
## Documentation Revamp

Currently the documenation is auto generated from various scripts. This also include scripts generating `arcade.__init__` and a few other things. We've discovered that this solution is not sustainable in the long run when needing to split up moduels as the codebase grows. It will be impossible maintain a script using `re` or `inspect` to achieve this.

Ideally we want the following:
* Versioned documentation so users can look up older versions
* Automatic doc building in current development branch
* Automatic doc building when tagging a release
* New documentation accessible minutes after releases/changes
* No cost related to documenation hosting?

## Scripts

* `utils/update_init.py`: Remove this and update `__init__.py` manually. WIth decent IDEs this should not be a problem. Warnings are even issued for members not being in `__all__`.
* `utils/create_resource_listings.py`: Probably need to keep this. Should trigger on doc build.
* `utils/create_quick_index.py`: Might still be needed, but probably needs to change slightly?
* `doc/conf.py`:
  * Calls `util/create_resources_listing.py`
  * Calls `util/update_quick_index.py`
  * Calls `doc/generate_example_thumbnails.py`: Still has a place in there
  * Connects `source-read -> source_read()` overriding how some moduels are genreated
  * Connects `build-finished -> post_process()` stripping submodules from member paths in docs (`arcade.sprite_list.SpriteList` transformed to `arcade.SpriteList`)

## Unit Test

We should add some unit test checking imports and docs holds up to a minimum standard.

* Check if `arcade.__init__.py` makes sense (`__all__` vs imports etc)
* Check if each module's `.rst` file covers all the public members
* Check if quick index makes sense

## TODO

- [x] Mode documents into approriate subdirectories to make the strucutre less flat
- [x] Move all scripts into the same location
- [x] Organize images better
- [x] Figure out if we can avoid recursive copy
- [x] Build a new api index using `api/`
- [x] Build a new quick index
- [ ] Unittest: api
- [ ] Unittest: quick index

**Comment by WebF0x** [comment]
Not sure if this fits here but when you Google "Arcade python documentation", many of the links are broken

Working:

- https://api.arcade.academy/en/latest/quick_index.html

Broken:

- https://arcade-pk.readthedocs.io/en/latest/arcade.html#
- https://api.arcade.academy/examples/index.html
- https://api.arcade.academy/quick_index.html
- https://api.arcade.academy/release_notes.html
- https://api.arcade.academy/sample_games.html

**Comment by einarf** [comment]
They will update over time. I don't think there's much we can do about this.

**Comment by einarf** [comment]
Closing this for now. A lot of things was revamped in 2.6
